spring:
  application:
    name: microservicio-devolucion
  profiles:
    active: prod
  autoconfigure:
    exclude:
      - org.springdoc.core.configuration.SpringDocHateoasConfiguration

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  level:
    root: INFO
    _store.devolucion: INFO
  file:
    name: logs/devolucion.log
