server:
  port: 8866 # Un puerto cualquiera solo para los tests

spring:
  application:
    name: microservicio-devolucion-test
  datasource:
    url: jdbc:h2:mem:db_devolucion_test;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

pedido-service:
  url: http://localhost:8083/api/store/pedidos
