services:
  - type: web
    name: eureka-server
    env: docker
    plan: free
    region: oregon
    rootDir: ./eureka-server

  - type: web
    name: mi-microservicio-pedido
    env: docker
    plan: free
    region: oregon
    rootDir: ./microservicio-pedido
    envVars:
      - key: PORT
        value: 8083
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: ${eureka_server_url}/eureka/

  - type: web
    name: api-gateway
    env: docker
    plan: free
    region: oregon
    rootDir: ./api-gateway
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: ${eureka_server_url}/eureka/