services:
  - type: web
    name: eureka-server
    env: docker
    plan: free
    region: oregon
    rootDir: ./eureka-server

  - type: web
    name: microservicio-pedido
    env: docker
    plan: free
    region: oregon
    rootDir: ./pedido
    envVars:
      - key: PORT
        value: 8083
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/

  - type: web
    name: api-gateway
    env: docker
    plan: free
    region: oregon
    rootDir: ./api-gateway
    envVars:
      - key: PORT
        value: 8080
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/

  # NUEVO: Microservicio de Pago
  - type: web
    name: microservicio-pago
    env: docker
    plan: free
    region: oregon
    rootDir: ./pago # Asegúrate de que esta sea la carpeta correcta en tu repositorio
    envVars:
      - key: PORT
        value: 8084
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
  
  # NUEVO: Microservicio de Inventario
  - type: web
    name: microservicio-inventario
    env: docker
    plan: free
    region: oregon
    rootDir: ./inventario
    envVars:
      - key: PORT
        value: 8088
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
  
  # NUEVO: Microservicio de cliente
  - type: web
    name: microservicio-cliente
    env: docker
    plan: free
    region: oregon
    rootDir: ./cliente
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/

  # NUEVO: Microservicio de producto
  - type: web
    name: microservicio-producto
    env: docker
    plan: free
    region: oregon
    rootDir: ./producto
    envVars:
      - key: PORT
        value: 8082
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/

  # NUEVO: Microservicio de envio
  - type: web
    name: microservicio-envio
    env: docker
    plan: free
    region: oregon
    rootDir: ./envio
    envVars:
      - key: PORT
        value: 8085
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/
  
  # NUEVO: Microservicio de resena
  - type: web
    name: microservicio-resena
    env: docker
    plan: free
    region: oregon
    rootDir: ./resena
    envVars:
      - key: PORT
        value: 8089
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URL
        value: https://eureka-server-mg8f.onrender.com/eureka/