server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: microservicio-pedido
              uri: lb://MICROSERVICIO-PEDIDO
              predicates:
                - Path=/microservicio-pedido/**
              filters:
                - StripPrefix=1

            - id: microservicio-pago
              uri: lb://MICROSERVICIO-PAGO
              predicates:
                - Path=/microservicio-pago/**
              filters:
                - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME}
    prefer-ip-address: false