server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: microservicio-pedido
              uri: lb://MICROSERVICIO-PEDIDO
              predicates:
                - Path=/microservicio-pedido/**
              filters:
                - StripPrefix=1

            - id: microservicio-pago
              uri: lb://MICROSERVICIO-PAGO
              predicates:
                - Path=/microservicio-pago/**
              filters:
                - StripPrefix=1

            - id: microservicio-inventario
              uri: lb://MICROSERVICIO-INVENTARIO
              predicates:
                - Path=/microservicio-inventario/**
              filters:
                - StripPrefix=1

            - id: microservicio-cliente
              uri: lb://MICROSERVICIO-CLIENTE
              predicates:
                - Path=/microservicio-cliente/**
              filters:
                - StripPrefix=1

            - id: microservicio-producto
              uri: lb://MICROSERVICIO-PRODUCTO
              predicates:
                - Path=/microservicio-producto/**
              filters:
                - StripPrefix=1

            - id: microservicio-envio
              uri: lb://MICROSERVICIO-ENVIO
              predicates:
                - Path=/microservicio-envio/**
              filters:
                - StripPrefix=1

            - id: microservicio-resena
              uri: lb://MICROSERVICIO-RESENA
              predicates:
                - Path=/microservicio-resena/**
              filters:
                - StripPrefix=1
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true