spring:
  application:
    name: microservicio-pago
  profiles:
    active: prod
  autoconfigure:
    exclude:
      - org.springdoc.core.configuration.SpringDocHateoasConfiguration

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG