server:
  port: 8081

spring:
  application:
    name: microservicio-cliente
  datasource:
    url: jdbc:h2:mem:db_404store_cliente;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  jwt:
    secret: clave-secreta-jwt-duoc-2026-demo-123456
    expiration-ms: 3600000
